### ISSUE TITLE
/get/group_ids api {"birth_year"=>"0" ...

### ISSUE THREAD

**Issue by rngadam** [transist/echidna-spider#19]
Looking at the logs, I only see birth_year 0? is this normal?

```
Mar 06 10:22:31 echidna1 echidna1:  [flyerhzm:spider][9914]: Tencent Weibo agent flyerhzm: Publishing tweet 242123132016149
Mar 06 10:22:31 echidna1 echidna1:  [flyerhzm:spider][9914]: Tencent Weibo agent flyerhzm: Cache hit: GET api/user/other_info {:name=>"songxiaobo"}
Mar 06 10:22:31 echidna1 echidna1:  [flyerhzm:streaming][9851]: /get_group_ids api received: {"birth_year"=>"0", "city"=>"上海", "gender"=>"male"}
```

**Comment by flyerhzm** [comment]
if user didn't set their birth year, it is 0, and streaming will add them
to group-other panel

On Wed, Mar 6, 2013 at 10:23 AM, Ricky Ng-Adam notifications@github.comwrote:

> Looking at the logs, I only see birth_year 0? is this normal?
> 
> Mar 06 10:22:31 echidna1 echidna1:  [flyerhzm:spider][9914]: Tencent Weibo agent flyerhzm: Publishing tweet 242123132016149
> Mar 06 10:22:31 echidna1 echidna1:  [flyerhzm:spider][9914]: Tencent Weibo agent flyerhzm: Cache hit: GET api/user/other_info {:name=>"songxiaobo"}
> Mar 06 10:22:31 echidna1 echidna1:  [flyerhzm:streaming][9851]: /get_group_ids api received: {"birth_year"=>"0", "city"=>"上海", "gender"=>"male"}
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transist/echidna-spider/issues/19
> .

## 

Best regards,
Richard Huang

http://huangzhimin.com
http://www.huangzhimin.comhttp://rails-bestpractices.com,
http://railsbp.com
https://github.com/flyerhzm http://github.com/flyerhzm,
https://github.com/railsbp
@flyerhzm, @railsbp

**Comment by rngadam** [comment]
what percentage of the users did not enter their birth year? Because I have yet to see anything else than zero...

**Comment by flyerhzm** [comment]
I will check with Rainux see the percentage of users he crawl last night

On Wed, Mar 6, 2013 at 10:31 AM, Ricky Ng-Adam notifications@github.comwrote:

> what percentage of the users did not enter their birth year? Because I
> have yet to see anything else than zero...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transist/echidna-spider/issues/19#issuecomment-14478850
> .

## 

Best regards,
Richard Huang

http://huangzhimin.com
http://www.huangzhimin.comhttp://rails-bestpractices.com,
http://railsbp.com
https://github.com/flyerhzm http://github.com/flyerhzm,
https://github.com/railsbp
@flyerhzm, @railsbp

**Comment by 0x1b2c** [comment]
I've did some grep in the cache data, we've sampled 119 users so far, and 99 of them didn't enter birth year, the percentage is 83%.

**Comment by 0x1b2c** [comment]
Hi Richard,

Looks like you should stop skillpages.com to send emails out with your
account, it's behavior should consider as spam.

**Comment by flyerhzm** [comment]
sorry, I already revoked its access, but I don't know why it still sent emails
