### ISSUE TITLE
same tweet id getting repeatedly published?

### ISSUE THREAD

**Issue by rngadam** [transist/echidna-spider#20]
Same tweet repeated multiple times?

example:

```
Mar  6 10:38:01 echidna1 [flyerhzm:spider][9914]: Tencent Weibo agent flyerhzm: Publishing tweet 242123132016149
```

multiple times:

```
$ sudo grep 242123132016149 /home/echidna/logs/rsyslog | wc -l
```

...this might explain why we're getting so many log lines

**Comment by 0x1b2c** [comment]
It's intentional, since I think it should not be spider's responsibility to check tweets duplication, and streaming should already handle duplicated users and tweets (@flyerhzm am I right?).

**Comment by 0x1b2c** [comment]
Also one reason for we got so many log lines from spider is, spider try to add user from each tweets' author, but this will not happen again since we already track sampled user by list and pre-added the users to system.
