### ISSUE TITLE
limitation reached repeated multiple times in the same second?

### ISSUE THREAD

**Issue by rngadam** [transist/echidna-spider#21]
Why is this message:

```
Mar 06 11:15:22 echidna1 echidna1:  [spider][6927]: Tencent Weibo agent agent0x001: Aborted tweets gathering: Tencent Weibo API calls limitation reached
```

...repeated 50 times in the same second when the limit is reached? Are we retrying multiple times when this happens?

**Comment by 0x1b2c** [comment]
I can't found log for time keyword "11:15:22" in syslog of echidna1, could you provide the full log?

**Comment by 0x1b2c** [comment]
I've saw similar duplication logs on echidna1 server, seems it's eventmachine's problem to run the periodic timer not strict. I've increased interval for tweets gathering from 5 secs to 30 secs, so it should be better.
