### ISSUE TITLE
user, group creation 

### ISSUE THREAD

**Issue by rngadam** [transist/echidna-spider#3]
echidna-streaming worker also expects add_user, add_group and add_user_to_group events as we are parsing the stream. Right now, echidna-spider only triggers add_tweet.

**Comment by flyerhzm** [comment]
@rainux, let's work together later

**Comment by 0x1b2c** [comment]
OK, I'll work on other stuff until you arrive our office.

**Comment by 0x1b2c** [comment]
Resolved in #6, @flyerhzm please help review it.
